export type Language = "en" | "ar" | "fa";

export type CommerceCopy = {
  flavor: string; selectFlavor: string; shop: string; browseCollection: string; search: string; searchPlaceholder: string; cart: string; cartEmpty: string; continueShopping: string; checkout: string; proceedCheckout: string; addToCart: string; addedToCart: string; whatsappOrder: string; callToOrder: string; priceToConfirm: string; availability: string; onRequest: string; available: string; outOfStock: string; details: string; specifications: string; quantity: string; description: string; category: string; brand: string; filters: string; clearFilters: string; applyFilters: string; allCategories: string; allBrands: string; priceRange: string; minPrice: string; maxPrice: string; sortBy: string; featured: string; priceLowHigh: string; priceHighLow: string; newest: string; results: string; noResults: string; placeholderNotice: string; productInquiry: string; subtotal: string; total: string; item: string; items: string; remove: string; orderSummary: string; checkoutTitle: string; customerName: string; phoneNumber: string; whatsappNumber: string; deliveryAddress: string; apartmentVilla: string; area: string; optionalNotes: string; notesPlaceholder: string; placeOrder: string; required: string; orderMessageIntro: string; orderMessageCustomer: string; orderMessagePhone: string; orderMessageWhatsApp: string; orderMessageAddress: string; orderMessageItems: string; orderMessageTotal: string; orderMessageNotes: string; validationName: string; validationPhone: string; validationAddress: string; secureNote: string; openDaily: string; home: string; about: string; contact: string; languages: string; adultsOnly: string; ageTitle: string; ageText: string; accept18: string; exit: string; ageNote: string; pageNotFound: string; backHome: string;
};

export const commerceCopy: Record<Language, CommerceCopy> = {
  en: { flavor: "Flavor", selectFlavor: "Select flavor",
    shop: "Shop", browseCollection: "Browse collection", search: "Search", searchPlaceholder: "Search by product, brand, category…", cart: "Cart", cartEmpty: "Your cart is waiting for a considered choice.", continueShopping: "Continue shopping", checkout: "Checkout", proceedCheckout: "Proceed to checkout", addToCart: "Add to cart", addedToCart: "Added to cart", whatsappOrder: "WhatsApp Order", callToOrder: "Call to Order", priceToConfirm: "Price to confirm", availability: "Availability", onRequest: "Confirm on WhatsApp", available: "Available", outOfStock: "Currently unavailable", details: "Product details", specifications: "Specifications", quantity: "Quantity", description: "Description", category: "Category", brand: "Brand", filters: "Filters", clearFilters: "Clear filters", applyFilters: "Apply filters", allCategories: "All categories", allBrands: "All brands", priceRange: "Price range", minPrice: "Min AED", maxPrice: "Max AED", sortBy: "Sort by", featured: "Featured", priceLowHigh: "Price: low to high", priceHighLow: "Price: high to low", newest: "Newest", results: "results", noResults: "No products match this edit yet.", placeholderNotice: "Catalog placeholder — replace with verified product information before publishing.", productInquiry: "Ask about this product", subtotal: "Subtotal", total: "Total", item: "item", items: "items", remove: "Remove", orderSummary: "Order summary", checkoutTitle: "Complete your order", customerName: "Customer name", phoneNumber: "Phone number", whatsappNumber: "WhatsApp number", deliveryAddress: "Delivery address", apartmentVilla: "Apartment / villa", area: "Area", optionalNotes: "Optional notes", notesPlaceholder: "Anything our team should know?", placeOrder: "Place Order on WhatsApp", required: "Required", orderMessageIntro: "Hello AL SAQAR, I would like to place an order.", orderMessageCustomer: "Customer", orderMessagePhone: "Phone", orderMessageWhatsApp: "WhatsApp", orderMessageAddress: "Delivery address", orderMessageItems: "Items", orderMessageTotal: "Total", orderMessageNotes: "Notes", validationName: "Please enter your name.", validationPhone: "Please enter a phone number.", validationAddress: "Please enter a delivery address.", secureNote: "No payment is taken online. Your order is confirmed by our team on WhatsApp.", openDaily: "Open daily", home: "Home", about: "About", contact: "Contact", languages: "Languages", adultsOnly: "Adults only · 18+", ageTitle: "A considered experience, for adults.", ageText: "You must be 18 years of age or older to enter this website.", accept18: "I am 18+", exit: "Exit", ageNote: "By entering, you confirm that you meet the legal age requirement.", pageNotFound: "Page not found", backHome: "Back to home",
  },
  ar: { flavor: "النكهة", selectFlavor: "اختر النكهة",
    shop: "المتجر", browseCollection: "تصفح المجموعة", search: "بحث", searchPlaceholder: "ابحث بالمنتج أو العلامة أو الفئة…", cart: "السلة", cartEmpty: "سلتك بانتظار اختيارك المدروس.", continueShopping: "متابعة التسوق", checkout: "الدفع", proceedCheckout: "المتابعة للدفع", addToCart: "أضف إلى السلة", addedToCart: "تمت الإضافة", whatsappOrder: "طلب عبر واتساب", callToOrder: "اتصل للطلب", priceToConfirm: "السعر عبر واتساب", availability: "التوفر", onRequest: "تأكيد عبر واتساب", available: "متوفر", outOfStock: "غير متوفر حاليًا", details: "تفاصيل المنتج", specifications: "المواصفات", quantity: "الكمية", description: "الوصف", category: "الفئة", brand: "العلامة", filters: "الفلاتر", clearFilters: "مسح الفلاتر", applyFilters: "تطبيق الفلاتر", allCategories: "كل الفئات", allBrands: "كل العلامات", priceRange: "نطاق السعر", minPrice: "الحد الأدنى AED", maxPrice: "الحد الأقصى AED", sortBy: "ترتيب حسب", featured: "مميز", priceLowHigh: "السعر: من الأقل", priceHighLow: "السعر: من الأعلى", newest: "الأحدث", results: "نتيجة", noResults: "لا توجد منتجات تطابق هذا الاختيار بعد.", placeholderNotice: "بيانات مؤقتة — استبدلها بمعلومات المنتج المؤكدة قبل النشر.", productInquiry: "اسأل عن هذا المنتج", subtotal: "المجموع الفرعي", total: "الإجمالي", item: "منتج", items: "منتجات", remove: "إزالة", orderSummary: "ملخص الطلب", checkoutTitle: "أكمل طلبك", customerName: "اسم العميل", phoneNumber: "رقم الهاتف", whatsappNumber: "رقم واتساب", deliveryAddress: "عنوان التوصيل", apartmentVilla: "الشقة / الفيلا", area: "المنطقة", optionalNotes: "ملاحظات اختيارية", notesPlaceholder: "هل هناك شيء يجب أن يعرفه فريقنا؟", placeOrder: "إرسال الطلب عبر واتساب", required: "مطلوب", orderMessageIntro: "مرحبًا السقار، أود تقديم طلب.", orderMessageCustomer: "العميل", orderMessagePhone: "الهاتف", orderMessageWhatsApp: "واتساب", orderMessageAddress: "عنوان التوصيل", orderMessageItems: "المنتجات", orderMessageTotal: "الإجمالي", orderMessageNotes: "الملاحظات", validationName: "يرجى إدخال اسمك.", validationPhone: "يرجى إدخال رقم الهاتف.", validationAddress: "يرجى إدخال عنوان التوصيل.", secureNote: "لا يتم تحصيل أي دفع إلكتروني. يؤكد فريقنا طلبك عبر واتساب.", openDaily: "مفتوح يوميًا", home: "الرئيسية", about: "عن المتجر", contact: "تواصل", languages: "اللغات", adultsOnly: "للبالغين فقط · 18+", ageTitle: "تجربة مدروسة، للبالغين.", ageText: "يجب أن يكون عمرك 18 عامًا أو أكثر لدخول هذا الموقع.", accept18: "عمري 18+", exit: "خروج", ageNote: "بدخولك، تؤكد استيفاءك لمتطلب السن القانوني.", pageNotFound: "الصفحة غير موجودة", backHome: "العودة للرئيسية",
  },
  fa: { flavor: "طعم", selectFlavor: "طعم را انتخاب کنید",
    shop: "فروشگاه", browseCollection: "مشاهده مجموعه", search: "جستجو", searchPlaceholder: "جستجو بر اساس محصول، برند یا دسته…", cart: "سبد خرید", cartEmpty: "سبد شما منتظر یک انتخاب سنجیده است.", continueShopping: "ادامه خرید", checkout: "تسویه حساب", proceedCheckout: "ادامه تسویه حساب", addToCart: "افزودن به سبد", addedToCart: "به سبد افزوده شد", whatsappOrder: "سفارش واتساپ", callToOrder: "تماس برای سفارش", priceToConfirm: "تأیید قیمت در واتساپ", availability: "موجودی", onRequest: "تأیید در واتساپ", available: "موجود", outOfStock: "فعلاً موجود نیست", details: "جزئیات محصول", specifications: "مشخصات", quantity: "تعداد", description: "توضیحات", category: "دسته", brand: "برند", filters: "فیلترها", clearFilters: "پاک کردن فیلترها", applyFilters: "اعمال فیلترها", allCategories: "همه دسته‌ها", allBrands: "همه برندها", priceRange: "محدوده قیمت", minPrice: "حداقل AED", maxPrice: "حداکثر AED", sortBy: "مرتب‌سازی بر اساس", featured: "ویژه", priceLowHigh: "قیمت: کم به زیاد", priceHighLow: "قیمت: زیاد به کم", newest: "جدیدترین", results: "نتیجه", noResults: "هنوز محصولی با این انتخاب مطابقت ندارد.", placeholderNotice: "داده موقت — پیش از انتشار با اطلاعات تأییدشده جایگزین کنید.", productInquiry: "درباره این محصول بپرسید", subtotal: "جمع جزء", total: "مجموع", item: "قلم", items: "قلم", remove: "حذف", orderSummary: "خلاصه سفارش", checkoutTitle: "سفارش خود را کامل کنید", customerName: "نام مشتری", phoneNumber: "شماره تلفن", whatsappNumber: "شماره واتساپ", deliveryAddress: "آدرس تحویل", apartmentVilla: "آپارتمان / ویلا", area: "منطقه", optionalNotes: "یادداشت اختیاری", notesPlaceholder: "آیا نکته‌ای هست که تیم ما بداند؟", placeOrder: "ثبت سفارش در واتساپ", required: "الزامی", orderMessageIntro: "سلام السقار، می‌خواهم سفارشی ثبت کنم.", orderMessageCustomer: "مشتری", orderMessagePhone: "تلفن", orderMessageWhatsApp: "واتساپ", orderMessageAddress: "آدرس تحویل", orderMessageItems: "محصولات", orderMessageTotal: "مجموع", orderMessageNotes: "یادداشت‌ها", validationName: "لطفاً نام خود را وارد کنید.", validationPhone: "لطفاً شماره تلفن را وارد کنید.", validationAddress: "لطفاً آدرس تحویل را وارد کنید.", secureNote: "پرداخت آنلاین دریافت نمی‌شود. تیم ما سفارش را در واتساپ تأیید می‌کند.", openDaily: "هر روز باز", home: "خانه", about: "درباره", contact: "تماس", languages: "زبان‌ها", adultsOnly: "فقط بزرگسالان · ۱۸+", ageTitle: "تجربه‌ای سنجیده، برای بزرگسالان.", ageText: "برای ورود به این وب‌سایت باید ۱۸ سال یا بیشتر داشته باشید.", accept18: "من ۱۸+ هستم", exit: "خروج", ageNote: "با ورود، تأیید می‌کنید که شرط سن قانونی را دارید.", pageNotFound: "صفحه پیدا نشد", backHome: "بازگشت به خانه",
  },
};

export const flavorAdminCopy: Record<Language, { flavors: string; addFlavor: string; editFlavor: string; deleteFlavor: string; save: string; cancel: string }> = {
  en: { flavors: "Flavors / Variants", addFlavor: "Add Flavor", editFlavor: "Edit Flavor", deleteFlavor: "Delete Flavor", save: "Save", cancel: "Cancel" },
  ar: { flavors: "النكهات / الخيارات", addFlavor: "إضافة نكهة", editFlavor: "تعديل النكهة", deleteFlavor: "حذف النكهة", save: "حفظ", cancel: "إلغاء" },
  fa: { flavors: "طعم‌ها / گزینه‌ها", addFlavor: "افزودن طعم", editFlavor: "ویرایش طعم", deleteFlavor: "حذف طعم", save: "ذخیره", cancel: "لغو" },
};

export const categoryLabels: Record<Language, Record<string, string>> = {
  en: { hookahs: "Hookahs", tobacco: "Tobacco", smokingDevices: "Smoking Devices", accessories: "Accessories", electronicDevices: "Electronic Devices", charcoalMore: "Charcoal & More" },
  ar: { hookahs: "الشيشة", tobacco: "التبغ", smokingDevices: "أجهزة التدخين", accessories: "الملحقات", electronicDevices: "الأجهزة الإلكترونية", charcoalMore: "الفحم والمزيد" },
  fa: { hookahs: "قلیان", tobacco: "تنباکو", smokingDevices: "دستگاه‌های دخانی", accessories: "لوازم جانبی", electronicDevices: "دستگاه‌های الکترونیکی", charcoalMore: "زغال و بیشتر" },
};

export const availabilityLabel = (language: Language, availability: string) => {
  const c = commerceCopy[language];
  return availability === "available" ? c.available : availability === "out_of_stock" ? c.outOfStock : c.onRequest;
};
